packages:
  # include packages in subfolders (e.g. apps/ and packages/)
  - "packages/**"
  - "apps/**"
  # if required, exclude some directories
  - "!**/test/**"
  - "!**/build/**"
  - "!**/dist/**"
